import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import UploadForm from "../components/UploadForm";

const Home: NextPage = () => {
  return (
    <div className='overflow-x-hidden overscroll-none'>
      <Head>
        <title>Nauti</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main className='flex flex-col'>
        <UploadForm />
      </main>
      {/* <footer className={styles.footer}>
        <span>
          <img src='/NautiIso.png' alt='Nauti Logo' className='w-14' />
        </span>
      </footer> */}
    </div>
  );
};

export default Home;
